# Site settings
baseurl = "https://example.org/"
languageCode = "en-us"
title = "BlackTie.co | Free Bootstrap Themes"
theme = "hugo-smpl-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]

# Enter your tracking code to enable Google analytics
googleAnalytics = ""

[params]
  # You can use Markdown for urls [text](//domain.tld/source)
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons.

  # To provide more meta data for search engines feel free to add a few information.
  # This lines will be inserted as meta tags.
  name = "Your Name"
  description = "Your Description"

  # Background
  [params.background]
    image = "assets/img/bg.jpg"

    # Enable and set background fade speed
    [params.background.fade]
      enable = true
      speed = 500

  # Logo section
  [params.logo]
    enable = true
    image = "assets/img/pharm_logo.png"
    alt = "BlackTie.co"
    width = "100"

  # Header section
  [params.header]
    enable = true
    title = "Brazo Pharmacy's<br>Awesome<br>Web Site"

  # Quote section
  [params.quote]
    enable = true
    text = "Believe in yourself! Have faith in your abilities! Without a humble but reasonable confidence in your own powers you cannot be successful or happy."

  # Social icons section
  # Add a modifier class to increase size
  # fa-lg, fa-2x, fa-3x, fa-4x, fa-5x
  # e.g., icon = "fa-instagram fa-lg"
  [params.social_icons]
    enable = true

  [[params.social]]
    title = "Dribbble"
    icon = "fa-dribbble"
    link = "http://dribbble.com/BrazoPharmacy"

  [[params.social]]
    title = "Twitter"
    icon = "fa-twitter"
    link = "http://twitter.com/Brazo_Pharmacy"

  [[params.social]]
    title = "Prescription Refills"
    icon = "fa-briefcase"
    link = "https://refills.brazopharmacy.com"

  [[params.social]]
    title = "Blog"
    icon = "fa-comment"
    link = "http://blog.brazopharmacy.com"

  [[params.social]]
    title = "Email Us!"
    icon = "fa-envelope"
    link = "mailto:contact@brazopharmacy.com"

  [[params.social]]
    title = "Newsletter"
    icon = "fa-coffee"
    link = "http://news.brazopharmacy.com"
